t: logger.ps1
	powershell -file parseit.ps1

logger.ps1:
	curl -sS -LO https://gist.githubusercontent.com/barsv/85c93b599a763206f47aec150fb41ca0/raw/6e68cb36aa6ffabb155e028aea4e408aea4de28f/logger.ps1
