PS_SW =
PS_SW += -version 2
PS_SW += -inputformat none
PS_SW += -noninteractive
PS_SW += -noprofile
PS_SW += -executionpolicy unrestricted

t2:
	powershell $(PS_SW) -file t2.ps1

t:
	powershell $(PS_SW) -file t.ps1

clean:
