t:
	powershell -version 1 -inputformat none -executionpolicy bypass -file t.ps1
t2:
	powershell -version 1 -inputformat none -executionpolicy bypass -file t.ps1 -quiet
t3:
	powershell -version 1 -inputformat none -executionpolicy bypass -file t.ps1_step1.ps1

clean:
	rm -f t.ps1_step1.ps1
